#+TITLE: emacs-my-manual
* Learning journey
** Doom Emacs more esoteric controls - a good place to start
*** Keybindings
**** Normal (sometimes any) mode
***** =g=
****** =gp= reselect paste
****** =g@= apply macro
****** =gc= comments - opens menu (=gcc= for just current line)
****** =gO= 'Imenu' - Like an index for the current document
****** =gx= evil-exchange (swap two visual selected regions)
****** =gy= yank text motion
****** =g=/g-= increment/decrement number at cursor
***** g Navigation
****** =gd/gD/gI/ga= look up definition/References/Implementations/Assignments
****** =gf= look up file
****** =gf= look up file
***** g Evaluation
****** =gr= eval region
****** =gR= eval buffer
***** Brackets
****** =]s= or =[s= next or previous error
****** =]space= or =[space= new line above or new line below
****** =]b= or =[b=  last/next buffer
****** =]f= or =[f=  last/next file
****** =gt= or =gT=  next-workspace/last-workspace
****** =]w= or =[w=  right-workspace/left-workspace - or tabs if you are using them
****** =]c= or =[c=  next/last comment
****** =]e= or =[e=  next/last error
****** =]F= or =[F=  next/last Frame
****** =]h= or =[h=  next/last outline next visible heading
****** =]m= or =[m=  next/last beginning of method
****** =]M= or =[M=  next/last end of method
****** =]o= or =[o=  new line above / new line below
***** Other
****** =zg= add spelling
****** =zw= remove spelling

**** Visual mode
***** =g=
****** =gp= alt paste
****** =g=/+g= increment number
****** =g-= decrement number
****** =gR= eval and replace region
***** Brackets
****** =]u= or =[u=  encode/decode url
****** =]x= or =[x=  encode/decode html entities
****** =]x= or =[x=  git next-hunk/last-hunk
****** =]t= or =[t=  git next-todo/last-todo


****** =gp= alt paste

***** Other

**** Visual mode

*** Evil
**** Goggles
- Shows selected area with a nice flash of background color when selections are made
**** Snipe
1. press =s/S= (lowercase for forwards and upper to go back) and then two letters of the thing on the line you are on that you want to jump to
2. press =Return= to go to that point OR press =s/S= again to move to next location in text (in that direction - lowercase for forwards and upper to go back)
3. =f =,F=, =t=, =T=, =;=, =,= still work as expected
**** Surround
Emulates surround.vim by Tope
**** Usage
***** Add surrounding

You can surround in visual-state with =S<textobject>= or =gS<textobject>=.
Or in normal-state with =ys<textobject>= or =yS<textobject>=.

***** Change surrounding

You can change a +surrounding+ with =cs<old-textobject><new-textobject>=.

***** Delete surrounding

You can delete a ( surrounding ) with =ds<textobject>=.

***** Add new surround pairs

A surround pair is this (trigger char with textual left and right
strings):

#+BEGIN_SRC emacs-lisp
(?> . ("<" . ">"))
#+END_SRC

or this (trigger char and calling a function):

#+BEGIN_SRC emacs-lisp
(?< . surround-read-tag)
#+END_SRC

You can add new by adding them to =evil-surround-pairs-alist=.
For more information do: =C-h v evil-surround-pairs-alist=.

=evil-surround-pairs-alist= is a buffer local variable, which means that
you can have different surround pairs in different modes. By default =<=
is used to insert a tag, in C++ this may not be useful - but inserting
angle brackets is, so you can add this:

#+BEGIN_SRC emacs-lisp
  (add-hook 'c++-mode-hook (lambda ()
                             (push '(?< . ("< " . " >")) evil-surround-pairs-alist)))
#+END_SRC

Don't worry about having two entries for =<= surround will take the
first.

Or in Emacs Lisp modes using ` to enter ` ' is quite useful, but not
adding a pair of ` (the default behavior if no entry in
=evil-surround-pairs-alist= is present), so you can do this:

#+BEGIN_SRC emacs-lisp
  (add-hook 'emacs-lisp-mode-hook (lambda ()
                                    (push '(?` . ("`" . "'")) evil-surround-pairs-alist)))
#+END_SRC

without affecting your Markdown surround pairs, where the default is useful.

To change the default =evil-surround-pairs-alist= you have to use =setq-default=,
for example to remove all default pairs:

#+BEGIN_SRC emacs-lisp
  (setq-default evil-surround-pairs-alist '())
#+END_SRC

or to add a pair that surrounds with two ` if you enter ~:

#+BEGIN_SRC emacs-lisp
  (setq-default evil-surround-pairs-alist
                (push '(?~ . ("``" . "``")) evil-surround-pairs-alist))
#+END_SRC
***** Add new surround pairs through creation of evil objects
You can create new evil objects that will be respected by evil-surround. Just use the following code:
#+BEGIN_SRC emacs-lisp
  ;; this macro was copied from here: https://stackoverflow.com/a/22418983/4921402
  (defmacro define-and-bind-quoted-text-object (name key start-regex end-regex)
    (let ((inner-name (make-symbol (concat "evil-inner-" name)))
          (outer-name (make-symbol (concat "evil-a-" name))))
      `(progn
         (evil-define-text-object ,inner-name (count &optional beg end type)
           (evil-select-paren ,start-regex ,end-regex beg end type count nil))
         (evil-define-text-object ,outer-name (count &optional beg end type)
           (evil-select-paren ,start-regex ,end-regex beg end type count t))
         (define-key evil-inner-text-objects-map ,key #',inner-name)
         (define-key evil-outer-text-objects-map ,key #',outer-name))))

  (define-and-bind-quoted-text-object "pipe" "|" "|" "|")
  (define-and-bind-quoted-text-object "slash" "/" "/" "/")
  (define-and-bind-quoted-text-object "asterisk" "*" "*" "*")
  (define-and-bind-quoted-text-object "dollar" "$" "\\$" "\\$") ;; sometimes your have to escape the regex
#+END_SRC
***** Add surround pairs for buffer-local text objects
Buffer-local text objects are useful for mode specific text objects that you
don't want polluting the global keymap. To make these objects work with
=evil-surround=, do the following (for example to bind pipes to =Q=):

#+BEGIN_SRC emacs-lisp
     (defvar evil-some-local-inner-keymap (make-sparse-keymap)
       "Inner text object test keymap")
     (defvar evil-some-local-outer-keymap (make-sparse-keymap)
       "Outer text object keymap")
     (define-key evil-some-local-inner-keymap "Q" #'evil-inner-pipe)
     (define-key evil-some-local-outer-keymap "Q" #'evil-a-pipe)
     (define-key evil-visual-state-local-map   "iQ" #'evil-inner-pipe)
     (define-key evil-operator-state-local-map "iQ" #'evil-inner-pipe)
     (define-key evil-visual-state-local-map   "aQ" #'evil-a-pipe)
     (define-key evil-operator-state-local-map "aQ" #'evil-a-pipe)
     (setq evil-surround-local-inner-text-object-map-list (list evil-some-local-inner-keymap))
     (setq evil-surround-local-outer-text-object-map-list (list evil-some-local-outer-keymap))
     (setq-local evil-surround-pairs-alist (append '((?Q "|" . "|")) evil-surround-pairs-alist))
#+END_SRC

note that the binding to =evil-some-local-(inner|outer)-keymap= is purely for organizational perpouses, you can skip that step and do:

#+BEGIN_SRC emacs-lisp
     (define-key evil-visual-state-local-map   "iQ" #'evil-inner-pipe)
     (define-key evil-operator-state-local-map "iQ" #'evil-inner-pipe)
     (define-key evil-visual-state-local-map   "aQ" #'evil-a-pipe)
     (define-key evil-operator-state-local-map "aQ" #'evil-a-pipe)
     (setq evil-surround-local-inner-text-object-map-list (list (lookup-key evil-operator-state-local-map "i")))
     (setq evil-surround-local-outer-text-object-map-list (list (lookup-key evil-operator-state-local-map "a")))
     (setq-local evil-surround-pairs-alist (append '((?Q "|" . "|")) evil-surround-pairs-alist))
#+END_SRC

***** Add new supported operators

You can add support for new operators by adding them to =evil-surround-operator-alist=.
For more information do: =C-h v evil-surround-operator-alist=.

By default, surround works with =evil-change= and =evil-delete=.
To add support for the evil-paredit package,
you need to add =evil-paredit-change= and =evil-paredit-delete=
to =evil-surround-operator-alist=, like so:

#+BEGIN_SRC emacs-lisp
  (add-to-list 'evil-surround-operator-alist
               '(evil-paredit-change . change))
  (add-to-list 'evil-surround-operator-alist
               '(evil-paredit-delete . delete))
#+END_SRC

***** Examples

Here are some usage examples (taken from [[https://github.com/tpope/vim-surround][surround.vim]]):

Press =cs"'= inside

#+BEGIN_EXAMPLE
    "Hello world!"
#+END_EXAMPLE

to change it to

#+BEGIN_EXAMPLE
    'Hello world!'
#+END_EXAMPLE

Now press =cs'<q>= to change it to

#+BEGIN_EXAMPLE
    <q>Hello world!</q>
#+END_EXAMPLE

To go full circle, press =cst"= to get

#+BEGIN_EXAMPLE
    "Hello world!"
#+END_EXAMPLE

To remove the delimiters entirely, press =ds"=.

#+BEGIN_EXAMPLE
    Hello world!
#+END_EXAMPLE

Now with the cursor on "Hello", press =ysiw]= (=iw= is a text object).

#+BEGIN_EXAMPLE
    [Hello] world!
#+END_EXAMPLE

Let's make that braces and add some space (use =}= instead of ={= for no
space): =cs]{=

#+BEGIN_EXAMPLE
    { Hello } world!
#+END_EXAMPLE

Now wrap the entire line in parentheses with =yssb= or =yss)=.

#+BEGIN_EXAMPLE
    ({ Hello } world!)
#+END_EXAMPLE

Revert to the original text: =ds{ds)=

#+BEGIN_EXAMPLE
    Hello world!
#+END_EXAMPLE

Emphasize hello: =ysiw<em>=

#+BEGIN_SRC html
  <em>Hello</em> world!
#+END_SRC

Finally, let's try out visual mode. Press a capital V (for linewise
visual mode) followed by =S<p class="important">=.

#+BEGIN_SRC html
  <p class="important">
    <em>Hello</em> world!
  </p>
#+END_SRC

Suppose you want to call a function on your visual selection or a text
object. You can simply press =f= instead of the aforementioned keys and
are then prompted for a functionname in the minibuffer, like with the
tags. So with:

#+BEGIN_EXAMPLE
    "Hello world!"
#+END_EXAMPLE

... after selecting the string, then pressing =Sf=, entering =print= and
pressing return you would get

#+BEGIN_SRC c
    print("Hello world!")
#+END_SRC

**** Traces
***** Highlights patters in =:s/abcdef/fedcba/=


**** lion - indents
- try glip. on a numbered list - pause after =i= to see options

